fix(bug): commit status for scheduled build won't be updated
go-vela/server pull request #1046
Opened 2024-01-25 01:54 UTC by timhuynh94

Ref [issue 841](https://github.com/go-vela/community/issues/841)

In GitHub you can update the commit status for a sha/context up to 1,000 times, see https://docs.github.com/en/enterprise-server@3.7/rest/commits/statuses#create-a-commit-status. The likelihood for this limit to be hit is higher with scheduled builds resulting in log errors like:

{"level":"error","msg":"unable to set commit status for build <org>/<repo>/9001: POST https://<domain>/api/v3/repos/<org>/<repo>/statuses/8968ddf24f66786c669ebd26fe83e3d4cf03a19c: 422 Validation Failed [{Resource:Status Field: Code:custom Message:This SHA and context has reached the maximum number of statuses.}]","time":"2023-07-31T19:00:13Z"}

The likelihood for this scenario to occur depend on schedule frequency and repository activity (or lack thereof).

A workaround is to make occasional commits to the repo.

Solution:
Don't send a status update to SCM for scheduled builds including pending status at the start. Most folks check Vela and they will see historical runs.

2024-01-25 16:43 UTC, ecrupper requested changes
QQ: does CreateBuild actually work? Otherwise, one comment on post.go. LGTM

2024-01-25 16:43 UTC, ecrupper commented on api/webhook/post.go
> +		}
We won't be receiving a webhook for schedule events

2024-01-26 16:48 UTC, timhuynh94 commented
> QQ: does CreateBuild actually work? Otherwise, one comment on post.go. LGTM

yes! We don't want to set the schedule build status to pending to begin with if we're not updating it!

2024-01-26 17:19 UTC, ecrupper approved these changes

2024-01-29 16:14 UTC, wass3rw3rk approved these changes

2024-01-29 17:01 UTC, merged