refactor(build)!: move build from types and nest the object
go-vela/server pull request #1111
Opened 2024-04-18 21:19 UTC by ecrupper

Follow up from https://github.com/go-vela/server/pull/1106, https://github.com/go-vela/server/pull/1095, and https://github.com/go-vela/server/pull/997

2024-04-23 15:41 UTC, wass3r requested changes
nice. some minor things. tested locally with WIP branches in sdk-go + worker. will need some tweak in UI to be able to parse new response, but looks good otherwise.

2024-04-23 16:15 UTC, wass3rw3rk commented on mock/server/build.go
> +  	},
ignore.. must have been the view i was looking at scrunching things and moving things out of alignment

2024-04-24 14:35 UTC, timhuynh94 approved these changes

2024-04-24 14:40 UTC, wass3rw3rk submitted a review, later dismissed

2024-04-24 14:42 UTC, wass3r approved these changes

2024-04-24 14:44 UTC, merged