enhance(mock): add dashboard responses from server in mock
go-vela/server pull request #1118
Opened 2024-05-02 20:09 UTC by ecrupper

Will need for SDK testing

2024-05-03 14:20 UTC, plyr4 requested changes

2024-05-03 14:20 UTC, plyr4 commented on mock/server/dashboard_test.go
> +		t.Errorf("error unmarshaling builds: %v", err)
```suggestion
		t.Errorf("error unmarshaling dashboard cards: %v", err)
```

2024-05-03 14:20 UTC, plyr4 commented on mock/server/dashboard_test.go
> +		t.Errorf("error unmarshaling build: %v", err)
```suggestion
		t.Errorf("error unmarshaling dashboard: %v", err)
```

2024-05-03 14:20 UTC, plyr4 commented on mock/server/dashboard.go
> +	// DashboardResp represents a JSON return for a single build.
```suggestion
	// DashboardResp represents a JSON return for a single dashboard.
```

2024-05-03 14:20 UTC, plyr4 commented on mock/server/dashboard.go
> +	// DashboardsResp represents a JSON return for one to many builds.
```suggestion
	// DashboardsResp represents a JSON return for one to many dashboards.
```

2024-05-03 14:58 UTC, plyr4 approved these changes

2024-05-06 14:25 UTC, KellyMerrick approved these changes
lgtm

2024-05-06 14:45 UTC, merged