feat(database): encrypt repo fields for enhanced security
go-vela/server pull request #321
Opened 2021-03-18 13:54 UTC by jbrockopp

Dependent on https://github.com/go-vela/types/pull/163

This change will introduce encryption for repo fields that are stored in the Vela database.

We've decided to use the Advanced Encryption Standard (`AES`) with a `256` bit key (a.k.a. `AES-256`):

https://en.wikipedia.org/wiki/Advanced_Encryption_Standard

> NOTE: This change is backward compatible. If you try fetching an unencrypted repo, everything will work as expected.
>
> We'll plan to offer some sort of utility that will assist in encrypting all existing repos in the database.

2021-03-26 14:47 UTC, davidvader requested changes
small typos

2021-03-26 14:47 UTC, davidvader commented on database/repo.go
> +	// decrypt the fields for the repo
```suggestion
	// encrypt the fields for the repo
```

2021-03-26 14:47 UTC, davidvader commented on database/repo.go
> +	// decrypt the fields for the repo
```suggestion
	// encrypt the fields for the repo
```

2021-03-30 13:03 UTC, jbrockopp commented on database/repo.go
> +	// decrypt the fields for the repo
fixed 👍

2021-03-30 13:03 UTC, jbrockopp commented on database/repo.go
> +	// decrypt the fields for the repo
fixed 👍

2021-03-31 13:36 UTC, matt-fevold approved these changes

2021-04-02 14:49 UTC, davidvader approved these changes

2021-04-02 15:01 UTC, merged