enhance(source): allow admin to customize oauth scopes
go-vela/server pull request #432
Opened 2021-06-17 22:15 UTC by JordanSussman

This change allows the Vela administrator to override the list of [OAuth scopes](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) by setting the `VELA_SOURCE_SCOPES` variable.

closes https://github.com/go-vela/community/issues/274

2021-06-21 15:31 UTC, wass3r submitted a review, later dismissed

2021-06-23 14:09 UTC, jbrockopp requested changes
Thanks for your contribution! 🎉

2021-06-23 14:09 UTC, jbrockopp commented on source/setup.go
> +		return fmt.Errorf("no scopes provided")
This is pretty minor but could we update this error message to mimic the other ones?

```suggestion
		return fmt.Errorf("no source scopes provided")
```

2021-06-23 14:25 UTC, jbrockopp approved these changes
LGTM

2021-06-24 16:48 UTC, wass3r approved these changes

2021-06-24 16:48 UTC, merged