Allow setting a webhook-specific server address
go-vela/server pull request #485
Opened 2021-09-28 17:59 UTC by cognifloyd

`VELA_SOURCE_WEBHOOK_ADDR` (or `SOURCE_WEBHOOK_ADDR`) allows setting an alternative to `VELA_ADDR`/`VELA_HOST` so that github and other source providers use this alternate, generally externally facing, address to send webhooks. This allows `VELA_ADDR` to match `VELA_API` in the UI so that the oauth login flow makes sense.

2021-09-28 18:55 UTC, meinenec requested changes

2021-09-28 18:55 UTC, meinenec commented on source/flags.go
> +			"differs from the server address the UI and oauth flows use, such as when the server" +
missing a space
```suggestion
			"differs from the server address the UI and oauth flows use, such as when the server " +
```

2021-09-28 19:16 UTC, cognifloyd commented
I'm not sure what to do with reviewdog's complaints as they have nothing to do with what I've changed. Can I ignore them?

2021-09-28 20:18 UTC, cognifloyd commented
All tests are green!

2021-09-28 23:46 UTC, cognifloyd commented
I just finished deploying a build of this in my on-prem k8s cluster. I was able to successfully auth with github, and receive a github webhook. Here's my test setup:

I have these resources an on-prem k8s cluster:
- vela-server: 1 service (type: ClusterIP) + 1 deployment (1 replica for testing; more replicas should work)
- vela-ui: 1 service (type: ClusterIP) + 1 deployment (1 replica for testing; more replicas should work)
- vela-worker: no service, 1 deployment (1 replica for testing; more replicas should work - each worker uses its pod IP as hostname for registration)

I have these nodes outside the k8s cluster:
- nginx load balancer inside the firewall that handles connections to vela-server and vela-ui (ssl termination + load balance) each on a separate internal domain. This proxy_passes to the kubernetes services for vela-server and vela-ui (below)
- nginx load balancer that handles external connections (ie webhooks from github) and then proxy_pass them to the internal domain (ie the internal load balancer)

2021-09-30 05:50 UTC, wass3r commented
generally speaking.. don't worry about golangci-lint unless it complains about something you are adding/changing specifically. we'll be going through to clean up in all the repos at some point.

if you don't mind, could you undo the `init`, `clone` change for now (since that occurs elsewhere also, it might end up in `go-vela/types` potentially). feel free to undo any of the other changes you made to satisfy the linter for code you didn't touch.

also, very exciting and cool to hear that you got something going in your cluster. fair to assume that you used the helm chart you shared?

2021-09-30 06:02 UTC, cognifloyd commented
K. I dropped the unrelated changes.

Yes, I used charts from https://github.com/cognifloyd/vela-charts
https://cognifloyd.github.io/vela-charts

2021-10-01 18:43 UTC, meinenec approved these changes

2021-10-01 19:03 UTC, kneal approved these changes
LGTM 🐬

2021-10-02 03:10 UTC, merged