enhance(templates): add toYaml function
go-vela/server pull request #523
Opened 2021-10-28 15:56 UTC by JordanSussman

Adding the custom Golang template function of `toYaml` that was copied from [github.com/helm/helm](https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/engine/funcs.go#L52). This new function makes it easy to directly consume variables within the underlying template as yaml.

This functionality was originally discussed within [slack](https://gophers.slack.com/archives/CNRRKE8KY/p1635286594017500).

2021-11-01 14:23 UTC, kneal submitted a review, later dismissed
LGTM 🐬

2021-11-01 16:43 UTC, jbrockopp submitted a review, later dismissed
LGTM

2021-11-01 18:50 UTC, wass3r requested changes

2021-11-01 18:50 UTC, wass3r commented on compiler/template/native/convert.go
> +// https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/engine/funcs.go#L83
looks like we need a nolint here :(

2021-11-02 03:19 UTC, jbrockopp approved these changes
LGTM

2021-11-02 05:50 UTC, wass3r approved these changes

2021-11-02 05:51 UTC, merged