add index on builds.created
go-vela/server pull request #545
Opened 2021-11-30 16:48 UTC by dtanner

Used for reporting - e.g. `where created > $some_epoch` to quickly and cheaply limit querying recent build metrics.

2021-12-01 02:48 UTC, wass3r requested changes
thanks for the additions! left some comments. super minor tweaks - mostly for consistency.

2021-12-01 02:48 UTC, wass3r commented on database/postgres/ddl/build.go
> +`
super picky but for consistency, can we add blank line after this and add a comment before the new query?

2021-12-01 02:48 UTC, wass3r commented on database/postgres/postgres.go
> +	err = c.Postgres.Exec(ddl.CreateBuildCreatedIndex).Error
missing comment before this for consistency

2021-12-01 02:48 UTC, wass3r commented on database/sqlite/ddl/build.go
> +	CreateBuildCreatedIndex = `
missing comment right before this new query.

2021-12-01 02:48 UTC, wass3r commented on database/sqlite/sqlite.go
> +	err = c.Sqlite.Exec(ddl.CreateBuildCreatedIndex).Error
missing comment before index creation.

additionally, i noticed between here and the postgres addition that the index is inserted in different spots. in the postgres version it was inserted at the end of the indexes and here after the other index on the build table. if i had to pick, i like the approach here better, but feel like it should be consistent between the two no matter where it happens.

2021-12-01 21:40 UTC, dtanner commented
i think all your comments were addressed @wass3r

2021-12-01 21:42 UTC, wass3r approved these changes

2021-12-02 14:53 UTC, jbrockopp approved these changes
LGTM

2021-12-02 20:05 UTC, merged