chore: Update contributing.md to link guidelines
go-vela/server pull request #606
Opened 2022-03-07 15:34 UTC by kaymckay

2022-03-07 23:11 UTC, ecrupper requested changes

2022-03-07 23:11 UTC, ecrupper commented on .github/CONTRIBUTING.md
> +* Review our [style guide](https://go-vela.github.io/docs/community/contributing_guidelines/#style-guide) to ensure your code is clean and consistent.
Do you think we could change this to be consistent with the format of the first two? 

```
[Review our style guide](https://go-vela.github.io/docs/community/contributing_guidelines/#style-guide) - ensure your code is clean and consistent.
```

2022-03-11 22:08 UTC, jbrockopp approved these changes
LGTM

2022-03-15 14:27 UTC, wass3r commented
@ecrupper merge is blocked by your review. can you re-review and merge if it's good?

thanks @kaymckay 🥳

2022-03-15 14:30 UTC, ecrupper approved these changes

2022-03-15 14:35 UTC, merged