feat(api/build): add endpoint to get build by id
go-vela/server pull request #646
Opened 2022-05-23 18:15 UTC by ecrupper

Part of the effort for creating a platform admin page with more worker visibility. Ideally, I wanted the ability to add something like `LastBuild` to the workers table, which would reference a build that could be viewed on the platform admin page. I also wanted something lightweight, such as simply storing the `ID`. So combining that, I coded up a couple endpoints that allow one to get a build by its ID. 

One endpoint is for users who have at least `write` access to the repo in question, and the other is for admins which bypasses that repo check.

2022-09-02 19:22 UTC, jbrockopp requested changes

2022-09-02 19:22 UTC, jbrockopp commented on router/search.go
> +// GET    /api/v1/search/build/:id .
plural?

2022-09-29 14:27 UTC, jbrockopp requested changes
I've reviewed the code and it LGTM! However, I had a question that may lead to a discussion.

> NOTE: I'm posting review as request for changes for visibility purposes.

I noticed that today, to query a build for a repo, we require the user has at least `read` level access:

https://github.com/go-vela/server/blob/8e8d0d456b0f57a978e996b85a20402841fabc5e/router/build.go#L56

Did we intentionally make this endpoint a higher access level (`write`)?

https://github.com/go-vela/server/blob/1de361fa72c98423be23ad3f3e7648b0800e1406/api/build.go#L492-L501

If so, could you share some of the thinking around why?

FWIW - I don't have strong concerns about the difference in access level requirements between the two endpoints.

More so, I'm trying to understand the reasoning behind it.

2022-09-29 15:11 UTC, ecrupper commented
Yeah, I'm not really sure why I chose `write`. I think complete parity with the current form of getting a build is the way we want to go. I'll change that now

2022-09-29 18:18 UTC, jbrockopp approved these changes
LGTM

2022-12-13 21:22 UTC, wass3r requested changes

2022-12-13 21:22 UTC, wass3r commented on api/admin/build.go
> +// swagger:operation GET /api/v1/admin/builds/:id admin AdminSingleBuild
with the latest changes, this needs to be updated to `/api/v1/admin/build/:id`

2022-12-13 21:47 UTC, plyr4 commented on api/build.go
> +
can we add a simple log here like `GetBuild` ?
https://github.com/go-vela/server/blob/c565a1d762bbd835b4f05f3d7318b9eda296757d/api/build.go#L955-L963

2022-12-13 22:04 UTC, ecrupper commented on api/build.go
> +	if perm == "none" {
The middleware won't capture the repo from the request, so it's necessary to have this perm check after retrieving the build. This preserves the integrity of the permission barrier.

2022-12-13 22:05 UTC, ecrupper commented on api/admin/build.go
> +func SingleBuild(c *gin.Context) {
There used to be an admin endpoint called `AllBuilds`, so I thought I'd follow that pattern. Now that it's no longer a pattern, I can change this.

2022-12-14 16:24 UTC, plyr4 approved these changes

2022-12-14 17:40 UTC, wass3r approved these changes

2022-12-14 17:41 UTC, merged