chore(logger): censor build author email for security compliance
go-vela/server pull request #667
Opened 2022-06-29 18:53 UTC by ecrupper

Addresses security concern that build author emails, which can be changed within GitHub enterprise to be a non-work email, were being logged. With this change, all http logs with the build as the body will now censor the email field. 

Abstracted this routine into a `sanitize` function, which can be used in case there are future concerns with logging practices.

2022-08-04 15:10 UTC, plyr4 submitted a review, later dismissed

2022-08-09 15:52 UTC, wass3r requested changes
the [lack of coverage](https://app.codecov.io/gh/go-vela/server/compare/667/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=go-vela#diff-cm91dGVyL21pZGRsZXdhcmUvbG9nZ2VyLmdv) in the report threw me off for a min.

when you do `sanitizeBuild := b` and modify a field, it will modify for both `b` and `santizeBuild`, since it's a pointer. you can get past it by dereferencing like `sanitizeBuild := *b` but you will see the tests fail then. turns out you never get past the `if m, ok := body.(map[string]interface{}); ok` check and always just return the original `body`.

if we can fix up the tests, this is good to go, i think.

2022-08-09 22:41 UTC, ecrupper commented
> the [lack of coverage](https://app.codecov.io/gh/go-vela/server/compare/667/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=go-vela#diff-cm91dGVyL21pZGRsZXdhcmUvbG9nZ2VyLmdv) in the report threw me off for a min.
> 
> when you do `sanitizeBuild := b` and modify a field, it will modify for both `b` and `santizeBuild`, since it's a pointer. you can get past it by dereferencing like `sanitizeBuild := *b` but you will see the test fail then. turns out you never get past the `if m, ok := body.(map[string]interface{}); ok` check and always just return the original `body`.
> 
> if we can fix up the tests, this is good to go, i think.

Good catch!

2022-08-15 15:52 UTC, plyr4 approved these changes

2022-08-18 21:25 UTC, wass3r approved these changes

2022-08-18 21:29 UTC, merged