enhance(scm/repo): mirror allowed events with sent events
go-vela/server pull request #679
Opened 2022-08-01 17:21 UTC by ecrupper

Closes https://github.com/go-vela/community/issues/539

Now that we store the `webhook_id` in the hooks table, we're able to edit the webhook whenever a user updates their repo settings. With this functionality, we will consume far less webhook payloads from the SCM and users won't have to deal with error messages for events they do not want enabled.

A couple things of note:

1. I added an `initialize` webhook whenever a repo is enabled. This ensures that when a user adjusts settings right after enabling their repo, we have record of the webhook_id to edit.
2. Since `tag` events are a sub-action of `push` events, I defaulted to always enabling push events regardless of selection. I think there is room for improvement on this: perhaps each `Allow<Event>` field becomes an array of actions rather than a bool? Food for thought.

Would love to hear thoughts!

2022-08-02 04:05 UTC, cognifloyd commented
Nice! From the issue description, we really need this.

I don't understand what the issue with push vs tag is. If you have time, could you post a few links to where the code needs to be disambiguated? I can also go looking next time I have some time to look.

2022-08-03 02:07 UTC, ecrupper commented
> I don't understand what the issue with push vs tag is. If you have time, could you post a few links to where the code needs to be disambiguated? I can also go looking next time I have some time to look.

For sure! The way GitHub is set up, they send tag events as a sub-action of a push ([Docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push)). We distinguish this in the code in [scm/webhook.go](https://github.com/go-vela/server/blob/66ef7d75000d03c51b4ca23689dfdc07979cddcc/scm/github/webhook.go#L178-L189). So if a user chose to unsubscribe to `push` events but not `tag` events, then we still need to handle all push events. I think a cleaner way would be to do some sort of `if r.GetAllowPush() || r.GetAllowTag()`, which I think I'll change now.

2022-08-03 02:25 UTC, cognifloyd approved these changes
Thanks for the links. That makes more sense.

Maybe update the PR description for future reviewers since that question has been resolved. 😄

2022-09-02 19:15 UTC, jbrockopp submitted a review, later dismissed
LGTM

2022-09-14 04:31 UTC, wass3r requested changes
in my testing against github.com this does not seem to work. when enabling a repo i get
```
Status 500 (unable to create initialization webhook for wass3r/vela-test: empty webhook repo_id provided)
```
we will need to set repo id or otherwise solve for this. the error comes from: https://github.com/go-vela/types/blob/ef95941428d9195503c3db067a9f27447b4dcc16/database/hook.go#L162

2022-09-15 05:08 UTC, wass3r requested changes
little bit of whack-a-mole.. now getting this error:
```
Status 500 (unable to create initialization webhook for wass3r/vela-test: empty webhook source_id provided)
```
😭

2022-09-15 13:38 UTC, ecrupper commented
Sorry about that! All required hook fields have been set now. I also included some extra testing in the scm `enable` function

2022-09-15 20:25 UTC, wass3r submitted a review, later dismissed
thanks for the fixes. tested on github.com and works great. nice work.

too bad we can't force update existing hooks in github.

2022-09-20 15:39 UTC, jbrockopp submitted a review, later dismissed
LGTM

2022-09-26 19:10 UTC, plyr4 submitted a review, later dismissed

2022-12-13 15:20 UTC, plyr4 approved these changes

2023-03-21 18:37 UTC, wass3r requested changes

2023-03-21 18:37 UTC, wass3r commented on api/repo/update.go
> +			}).Infof("platform admin updating repo webhook events for repo %s", r.GetFullName())
can we move it to _after_ we get the user, because it's not until then, that user is actually getting used?

2023-03-21 19:05 UTC, wass3r approved these changes

2023-03-22 19:58 UTC, wass3rw3rk approved these changes

2023-03-23 15:01 UTC, jbrockopp approved these changes
LGTM

2023-03-23 15:09 UTC, merged