enhance(scm/webhook): handle default branch change and archived repo
go-vela/server pull request #706
Opened 2022-09-28 20:52 UTC by ecrupper

Closes https://github.com/go-vela/community/issues/325

Closes https://github.com/go-vela/community/issues/659

Building off the work done in https://github.com/go-vela/server/pull/556, using repository events can help maintain parity between GitHub repos and their Vela equivalent.

2022-10-11 02:31 UTC, cognifloyd submitted a review, later dismissed
LGTM

2022-11-15 17:17 UTC, jbrockopp approved these changes
LGTM

2022-12-09 20:52 UTC, wass3r requested changes
lgtm - one minor request

2022-12-09 20:52 UTC, wass3r commented on api/webhook.go
> +			c.JSON(http.StatusOK, fmt.Sprintf("no build to process, repository %s.", h.GetEventAction()))
let's be more specific on what action took place here. we are making a changed in the database - we should call that out.

2022-12-13 17:19 UTC, wass3r approved these changes

2022-12-13 17:49 UTC, plyr4 approved these changes

2022-12-13 20:44 UTC, merged