fix(secret): check org casing for repo secret creation
go-vela/server pull request #708
Opened 2022-09-29 19:36 UTC by ecrupper

Overlooked a potential casing mishap intended to be fixed in this PR: https://github.com/go-vela/server/pull/700.

Previously only the repo casing was checked. This will verify both org and repo casing for creating repo secrets outside the UI.

2022-09-30 03:46 UTC, KellyMerrick approved these changes
lgtm

2022-09-30 13:20 UTC, wass3r requested changes

2022-09-30 13:20 UTC, wass3r commented on scm/service.go
>  	// the name of the repo in the SCM.
org and name

2022-10-03 18:30 UTC, KellyMerrick approved these changes
lgtm

2022-10-03 20:22 UTC, plyr4 approved these changes

2022-10-03 20:24 UTC, wass3r approved these changes

2022-10-03 20:30 UTC, merged