feat(templates): support same-repo templates using build commit
go-vela/server pull request #713
Opened 2022-10-06 21:35 UTC by ecrupper

When working with templates that are found in the same repo as the Vela file, any live edits to the templates requires the users to reference their specific branch in the templates block. Example: 
```yaml
templates:
  - name: sample
    source: https://github.com/<org>/<repo>/path/template.yml@feature-branch
    type: github
```

With this change, users can specify the type `commit` in their templates block, which will automatically fetch the template from the commit associated with the build. Example: 
```yaml
templates:
  - name: sample
    source: path/template.yml
    type: commit
```

2022-10-07 15:41 UTC, JordanSussman commented
@ecrupper I feel like we should have the `type` be either `github-commit` or `commit-github` incase we want to add additional source code systems in the provider.

2022-10-11 15:41 UTC, cognifloyd requested changes
Very nice!

I think we should stick with `commit` (or something similar) that does not mention github. See my comment.

I have one nitpick about the test. Otherwise, I say this is good to go!

2022-10-11 15:41 UTC, cognifloyd commented on compiler/native/expand_test.go
> +		build, err := compiler.ExpandSteps(&yaml.Build{Steps: steps, Services: yaml.ServiceSlice{}, Environment: globalEnvironment}, test.tmpls)
Would you please use `t.Run()` here? That makes selecting subtests easier in Goland.

2022-10-11 15:43 UTC, wass3r commented
this would be really nice for local pipeline execution via `vela exec pipeline` - even without checking code in. but i think the current implementation doesn't suit itself for that. part of the reason i thought this can be scm agnostic and the type be `relative` or `file`. thoughts around that?

2022-10-11 15:48 UTC, cognifloyd commented
> this would be really nice for local pipeline execution via `vela exec pipeline` - even without checking code in. but i think the current implementation doesn't suit itself for that. part of the reason i thought this can be scm agnostic and the type be `relative` or `file`. thoughts around that?

Is that what `c.local` bit does?

https://github.com/go-vela/server/blob/56932446fdc545d44162da499f7318ad34994c77/compiler/native/expand.go#L170-L179

I kind of like `relative` - but that might suggest that it is relative to the current file vs relative to the repo root.
I think I could grow to like `file` even better. The more I think about this one, I think I like it a lot.

2022-10-11 15:59 UTC, wass3r commented
> Is that what c.local bit does?

busted! forgot about that. 🫣

2022-12-13 17:18 UTC, wass3r approved these changes

2022-12-13 17:18 UTC, wass3r commented
@cognifloyd i think your feedback is addressed

@ecrupper we will need to add to docs too

2022-12-13 17:46 UTC, cognifloyd approved these changes

2022-12-13 19:17 UTC, merged