feat(build_tokens): server changes for build token implementation
go-vela/server pull request #765
Opened 2023-02-21 22:08 UTC by ecrupper

Server PR for Epic 1: Build Tokens.

Changes:

- Conversion of `router/middleware/token` package to `router/middleware/auth`, which will now only retrieve auth headers from http requests, rather than generate/parse tokens
- Creation of `internal/token` package, which features a `manager` that is set up in the context using various new flags added to `main.go`. In brief, it's a one-stop-shop for token minting and validating and offers configurability to a degree.
- Additional claims added to `Claims` struct, including information about the token type as well as relevant fields for that token (build tokens have build ids and repo).
- Removal of global permissions for agents
- Worker endpoints used for check in (POST / PUT) have been put behind `MustWorker()` permissions check, which validates the symmetric token shared between server and worker
- Build/Step/Service/Log update endpoints have been put behind `MustBuildAccess()` permissions check, which validates the build token, which is provided as a unique auth scope for each build.
- Add GET endpoint for retrieving a build token, which validates the build's status and creates a build token
- Addition of a private key, which will be seeded in the server environment, much like the secret, which will be used to sign and validate all tokens.
- Updates made to `MustSecretAdmin` which will scope requests with build token auth based on the repo within the token
- Claims will be established in the context for baseAPI endpoints before the user

2023-02-21 22:10 UTC, plyr4 commented on .github/workflows/publish.yml
> -# name of the action
revert deletion?

2023-02-21 22:22 UTC, wass3r approved these changes

2023-02-23 16:26 UTC, wass3r submitted a review, later dismissed

2023-02-23 16:30 UTC, plyr4 requested changes

2023-02-23 16:30 UTC, plyr4 commented on internal/token/compose.go
> +// Compose generates an refresh and access token pair unique
```suggestion
// Compose generates a refresh and access token pair unique
```

2023-02-23 16:41 UTC, ecrupper commented on internal/token/compose.go
> +// Compose generates an refresh and access token pair unique
Nice catch!!

2023-02-23 16:43 UTC, wass3r approved these changes

2023-02-23 18:19 UTC, jbrockopp requested changes
proposal?

2023-02-23 21:06 UTC, ecrupper commented
> proposal?

https://github.com/go-vela/community/pull/755

2023-02-23 22:29 UTC, wass3r approved these changes

2023-02-23 22:38 UTC, plyr4 approved these changes

2023-02-23 22:39 UTC, timhuynh94 approved these changes

2023-02-23 22:44 UTC, merged

2023-02-27 15:51 UTC, cognifloyd approved these changes