refactor(database): move secret logic into separate package
go-vela/server pull request #782
Opened 2023-03-04 17:47 UTC by jbrockopp

Based off of https://github.com/go-vela/server/pull/574, https://github.com/go-vela/server/pull/663, https://github.com/go-vela/server/pull/687, https://github.com/go-vela/server/pull/692 and https://github.com/go-vela/server/pull/721 and https://github.com/go-vela/server/pull/722

This change continues the refactor efforts initially introduced in the above PRs.

This adds a new `secret` package to the `github.com/go-vela/server/database` package.

This contains a `SecretService` interface declaring all functions necessary for worker based interactions with the database:

https://github.com/go-vela/server/blob/6bf34484bbbf66c259bb6116132f5c72d47adeea/database/secret/service.go#L11-L49

This package also contains the `engine` which implements the above service interface:

https://github.com/go-vela/server/blob/6bf34484bbbf66c259bb6116132f5c72d47adeea/database/secret/secret.go#L25-L39

This `engine` contains no raw SQL queries for integrating with the `secrets` table.

Instead, we leverage our DB library's (https://gorm.io/) agnostic abstraction for integrating with that table.

2023-03-24 03:16 UTC, cognifloyd requested changes
This is so much cleaner! Thanks for working on this.

I started reviewing and have a few comments/requests about handling all secret types.

2023-03-24 03:16 UTC, cognifloyd commented on database/secret/create.go
> +	}
It looks like this handles Team(Shared) and Repo secrets here and in the error message below. What about org secrets? There isn't a repo name for org secrets.

Could you add test cases for each of the secret types?

2023-03-24 03:16 UTC, cognifloyd commented on database/secret/delete.go
> +	}
Same as `Create`. Please add tests to ensure this can delete all secret types: Org, Team, Repo.

2023-03-24 03:16 UTC, cognifloyd commented on database/secret/update.go
> +	}
Same as `Create`. Please add tests to ensure this can update all secret types: Org, Team, Repo.

2023-03-24 05:02 UTC, cognifloyd reviewed
On the count methods, the `filters` arg looks like a new feature. Where/when might this be used?

Also, where are we planning to use the count all secrets (database `CountSecrets`) method? I don't see anything that uses it in the native secrets engine.

2023-03-24 13:19 UTC, cognifloyd commented on database/secret/service.go
> +	// DeleteSecret defines a function that deletes an existing repo.
```suggestion
	// CreateSecret defines a function that creates a new secret.
	CreateSecret(*library.Secret) error
	// DeleteSecret defines a function that deletes an existing secret.
```

2023-03-24 13:20 UTC, cognifloyd commented on database/secret/service.go
> +	// UpdateSecret defines a function that updates an existing repo.
```suggestion
	// UpdateSecret defines a function that updates an existing secret.
```

2023-03-27 20:12 UTC, jbrockopp commented on database/secret/count_team.go
> +		Where("team = ?", team).
This code replicates the previous behavior:

https://github.com/go-vela/server/blob/8b1b8575e5398054058ab524b015efd5fe6a69ed/database/postgres/dml/secret.go#L84-L94

2023-03-28 00:50 UTC, cognifloyd approved these changes
Awesome. Thank you!

2023-03-30 14:30 UTC, plyr4 submitted a review, later dismissed
extremely minor comment typos

2023-03-30 14:30 UTC, plyr4 commented on database/secret/secret_test.go
> +		t.Errorf("unable to create new sqlite repo engine: %v", err)
```suggestion
		t.Errorf("unable to create new sqlite secret engine: %v", err)
```

2023-04-03 19:03 UTC, cognifloyd approved these changes

2023-04-10 19:47 UTC, ecrupper approved these changes
Nice — LGTM

2023-04-10 19:49 UTC, merged