refactor(api): move log logic into separate package
go-vela/server pull request #855
Opened 2023-05-19 22:29 UTC by ecrupper

Based off of https://github.com/go-vela/server/pull/615 https://github.com/go-vela/server/pull/754 https://github.com/go-vela/server/pull/809 https://github.com/go-vela/server/pull/828 https://github.com/go-vela/server/pull/829 https://github.com/go-vela/server/pull/847 https://github.com/go-vela/server/pull/848 https://github.com/go-vela/server/pull/849 https://github.com/go-vela/server/pull/851 and https://github.com/go-vela/server/pull/853

This change continues the refactor efforts initially introduced in the above PRs.

This adds a new `log` package to the `github.com/go-vela/server/api` package.

This contains all the same handlers that existed previously but with each of them within their own file.

Also changed `GetBuildLogs` to `ListLogsForBuild` to stay consistent.

2023-05-20 02:18 UTC, cognifloyd requested changes

2023-05-20 02:18 UTC, cognifloyd commented on api/log/list_build.go
> +	}).Infof("reading logs for build %s", entry)
```suggestion
	}).Infof("listing logs for build %s", entry)
```

2023-05-20 02:18 UTC, cognifloyd commented on api/log/list_build.go
> +		retErr := fmt.Errorf("unable to get logs for build %s: %w", entry, err)
```suggestion
		retErr := fmt.Errorf("unable to list logs for build %s: %w", entry, err)
```

2023-05-20 02:20 UTC, cognifloyd commented on api/log/create_service.go
> +	"github.com/sirupsen/logrus"
Could we remove the blank lines between github imports and sort them? Same for the other files.

2023-05-20 02:33 UTC, cognifloyd commented on api/log/get_service.go
> +//   description: ID of the service
This is the service number (the number in the build) not the ID (the globally unique service ID) right?

Could we say `Number of the service in the build`? Or more succinctly `Service number` (similar to how we have `Step number` on the step log handlers).

If so, then please also do the same as `GetServiceLog` for `UpdateServiceLog` and `DeleteServiceLog`.

2023-05-22 14:12 UTC, cognifloyd approved these changes

2023-05-22 14:18 UTC, plyr4 approved these changes

2023-05-22 15:07 UTC, merged