refactor(database): return build object on created and updated
go-vela/server pull request #884
Opened 2023-06-13 17:02 UTC by ecrupper

Continuing effort from these: https://github.com/go-vela/server/pull/861, https://github.com/go-vela/server/pull/882

2023-06-13 23:43 UTC, cognifloyd approved these changes

2023-06-14 13:25 UTC, jbrockopp requested changes

2023-06-14 13:25 UTC, jbrockopp commented on database/build/create.go
We should crop the `build` object here like we did in `update.go`:

```go
	// crop build if any columns are too large
	build = build.Crop()
```

2023-06-14 13:25 UTC, jbrockopp commented on database/build/update.go
> +	build = build.Crop()
Can we make sure we also do this in the `CreateBuild()` function?

2023-06-14 16:17 UTC, cognifloyd approved these changes

2023-06-15 15:24 UTC, jbrockopp approved these changes
LGTM

2023-06-15 15:59 UTC, timhuynh94 approved these changes

2023-06-15 16:07 UTC, merged