fix(schedules): criteria for triggering a build
go-vela/server pull request #893
Opened 2023-06-26 13:01 UTC by jbrockopp

2023-07-06 02:24 UTC, JordanSussman approved these changes

2023-07-06 14:40 UTC, plyr4 requested changes

2023-07-06 14:40 UTC, plyr4 commented on cmd/vela-server/schedule.go
> +		nextTime, err := gronx.NextTickAfter(s.GetEntry(), time.Unix(s.GetScheduledAt(), 0).UTC(), true)
avoid using stale data when multiple servers are processing simultaneously 

```suggestion
		nextTime, err := gronx.NextTickAfter(schedule.GetEntry(), time.Unix(schedule.GetScheduledAt(), 0).UTC(), true)
```

2023-07-06 14:40 UTC, plyr4 commented on cmd/vela-server/schedule.go
> +			logrus.Tracef("ignoring to schedule build for %s", s.GetName())
```suggestion
			logrus.Tracef("ignoring to schedule build for %s", schedule.GetName())
```

2023-07-06 14:40 UTC, plyr4 commented on cmd/vela-server/schedule.go
> +			logrus.WithError(err).Warnf("%s for %s", baseErr, s.GetName())
```suggestion
			logrus.WithError(err).Warnf("%s for %s", baseErr, schedule.GetName())
```

2023-07-06 14:40 UTC, plyr4 commented on cmd/vela-server/schedule.go
> +			logrus.WithError(err).Warnf("%s for %s", baseErr, s.GetName())
```suggestion
			logrus.WithError(err).Warnf("%s for %s", baseErr, schedule.GetName())
```

2023-07-06 14:40 UTC, plyr4 commented on cmd/vela-server/schedule.go
> +			logrus.Tracef("waiting to schedule build for %s", s.GetName())
```suggestion
			logrus.Tracef("waiting to schedule build for %s", schedule.GetName())
```

2023-07-06 14:40 UTC, plyr4 commented on cmd/vela-server/schedule.go
> +			logrus.Tracef("waiting to schedule build for %s", s.GetName())
```suggestion
			logrus.Tracef("waiting to schedule build for %s", schedule.GetName())
```

2023-07-06 14:41 UTC, plyr4 commented
looks good, just some minor tweaks to use the schedule we fetch from the database while iterating

2023-07-07 16:39 UTC, ecrupper commented on cmd/vela-server/schedule.go
> +			logrus.WithError(err).Warnf("%s %s", scheduleErr, schedule.GetName())
```suggestion
			logrus.WithError(err).Warnf("%s %s: %v", scheduleErr, schedule.GetName(), err)
```
Thoughts on passing the error we get from `processSchedule` into the logs?

2023-07-07 17:28 UTC, JordanSussman commented
@jbrockopp should the `test-docker-compose.yml` file be removed?

2023-07-07 18:29 UTC, jbrockopp commented
@JordanSussman yeah I plan to remove that but initially had it there for testing purposes for Easton and I.

I'm finalizing one last change here shortly and then I'll also remove that file.

2023-07-07 20:11 UTC, ecrupper approved these changes

2023-07-07 20:22 UTC, wass3rw3rk approved these changes
thanks 👍🏼

2023-07-10 14:27 UTC, plyr4 approved these changes

2023-07-10 14:29 UTC, merged